# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friendstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='followers_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
